# Generated by Django 4.2.29 on 2026-03-20 23:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('card', 'Tarjeta'), ('bank', 'Cuenta bancaria'), ('mercadopago', 'Mercado Pago')], max_length=20, verbose_name='tipo')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('is_default', models.BooleanField(default=False, verbose_name='método predeterminado')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='monto')),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('method', models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('paypal', 'PayPal'), ('mercadopago', 'Mercado Pago')], default='bank_transfer', max_length=20, verbose_name='método')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='banco')),
                ('bank_account_last4', models.CharField(blank=True, max_length=4, verbose_name='últimos 4 dígitos')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'payout_orders',
            },
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('sale', 'Venta'), ('refund_fee', 'Tarifa de reembolso'), ('subscription', 'Suscripción'), ('other', 'Otro')], max_length=20, verbose_name='fuente')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ingreso de plataforma',
                'verbose_name_plural': 'ingresos de plataforma',
                'db_table': 'platform_revenue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('sale', 'Venta'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste')], default='sale', max_length=20, verbose_name='fuente')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto bruto')),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='tasa de comisión')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto neto')),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible para retiro')),
                ('payout_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ganancia',
                'verbose_name_plural': 'ganancias',
                'db_table': 'seller_earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Venta'), ('platform_fee', 'Comisión de plataforma'), ('payout', 'Pago a vendedor'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste'), ('withdrawal', 'Retiro')], max_length=20, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=100)),
                ('mercadopago_merchant_order_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.orderitem')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.payout')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
