# Generated by Django 4.2.29 on 2026-03-20 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerearning',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_earnings', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sellerearning',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_seller_earnings', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='sellerearning',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='payments.payout'),
        ),
        migrations.AddField(
            model_name='sellerearning',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformrevenue',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_revenue', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payoutorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='payoutorder',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='payoutorder',
            name='payout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payout'),
        ),
        migrations.AddField(
            model_name='payout',
            name='orders',
            field=models.ManyToManyField(through='payments.PayoutOrder', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payout',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_9aa2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerearning',
            index=models.Index(fields=['seller', 'is_available'], name='seller_earn_seller__5e6c47_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerearning',
            index=models.Index(fields=['created_at'], name='seller_earn_created_34c40b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payoutorder',
            unique_together={('payout', 'order', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', 'status'], name='payouts_seller__d7cf46_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['requested_at'], name='payouts_request_9ecb76_idx'),
        ),
    ]
