# Generated by Django 4.2.29 on 2026-03-20 23:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('seller', 'Vendedor'), ('buyer', 'Comprador')], default='buyer', max_length=20, verbose_name='rol')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('pending', 'Pendiente de verificación'), ('suspended', 'Suspendido'), ('banned', 'Bloqueado')], default='active', max_length=20, verbose_name='estado')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='biografía')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='nombre de empresa')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='RFC/TIN')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('mercadopago_customer_id', models.CharField(blank=True, max_length=100)),
                ('mercadopago_seller_id', models.CharField(blank=True, max_length=100)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('payout_method', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('transfer', 'Transferencia bancaria')], default='mercadopago', max_length=20, verbose_name='método de pago')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='nombre del banco')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='número de cuenta')),
                ('bank_clabe', models.CharField(blank=True, max_length=20, verbose_name='CLABE interbancaria')),
                ('language', models.CharField(default='es', max_length=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('email_notifications', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'db_table': 'user_sessions',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('shipping', 'Envío'), ('billing', 'Facturación')], default='shipping', max_length=20)),
                ('street', models.CharField(max_length=255, verbose_name='calle')),
                ('exterior_number', models.CharField(blank=True, max_length=20, verbose_name='número exterior')),
                ('interior_number', models.CharField(blank=True, max_length=20, verbose_name='número interior')),
                ('colony', models.CharField(max_length=255, verbose_name='colonia')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='país')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='razón social')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='RFC')),
                ('use_company_address', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, verbose_name='dirección principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'db_table': 'user_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('active_products', models.PositiveIntegerField(default=0)),
                ('pending_products', models.PositiveIntegerField(default=0)),
                ('rejected_products', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estadística de vendedor',
                'verbose_name_plural': 'estadísticas de vendedores',
                'db_table': 'seller_stats',
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_preference', models.CharField(default='es', max_length=10)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notify_new_products', models.BooleanField(default=True)),
                ('notify_price_drops', models.BooleanField(default=True)),
                ('notify_seller_news', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_categories', models.ManyToManyField(blank=True, to='products.category')),
                ('favorite_products', models.ManyToManyField(blank=True, to='products.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de comprador',
                'verbose_name_plural': 'perfiles de compradores',
                'db_table': 'buyer_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='users_role_bc23be_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
