# Generated by Django 4.2.29 on 2026-03-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_verified',
            field=models.BooleanField(default=False, verbose_name='cuenta verificada'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_rut',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT titular cuenta'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='mercadopago_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email Mercado Pago'),
        ),
        migrations.AddField(
            model_name='user',
            name='mercadopago_verified',
            field=models.BooleanField(default=False, verbose_name='Mercado Pago verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_verified',
            field=models.BooleanField(default=False, verbose_name='nombres verificados'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_verified',
            field=models.BooleanField(default=False, verbose_name='contraseña verificada'),
        ),
        migrations.AddField(
            model_name='user',
            name='rut_verified',
            field=models.BooleanField(default=False, verbose_name='RUT verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT/TIN'),
        ),
    ]
