# Generated by Django 4.2.29 on 2026-03-28 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_finance_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='favorite_products',
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, help_text='RUT sin puntos, con guión y dígito verificador. Ej: 12345678-5', max_length=20, verbose_name='RUT')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='apellidos')),
                ('face_photo', models.ImageField(blank=True, help_text='Foto clara del rostro (selfie)', null=True, upload_to='verification/face/', verbose_name='foto de rostro')),
                ('id_card_front', models.ImageField(blank=True, help_text='Foto del anverso del carnet de identidad', null=True, upload_to='verification/id/', verbose_name='carnet - anverso')),
                ('id_card_back', models.ImageField(blank=True, help_text='Foto del reverso del carnet de identidad', null=True, upload_to='verification/id/', verbose_name='carnet - reverso')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='estado')),
                ('rut_verified', models.BooleanField(default=False, verbose_name='RUT verificado')),
                ('name_verified', models.BooleanField(default=False, verbose_name='Nombre verificado')),
                ('photo_verified', models.BooleanField(default=False, verbose_name='Foto verificada')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notas del administrador')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='razón de rechazo')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verificación de usuario',
                'verbose_name_plural': 'verificaciones de usuarios',
                'db_table': 'user_verifications',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mercadopago_card_id', models.CharField(blank=True, max_length=100, verbose_name='ID de tarjeta MP')),
                ('mercadopago_customer_id', models.CharField(blank=True, max_length=100, verbose_name='ID de cliente MP')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='últimos 4 dígitos')),
                ('card_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], default='credit', max_length=10, verbose_name='tipo')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='marca')),
                ('card_holder_name', models.CharField(blank=True, max_length=100, verbose_name='nombre del titular')),
                ('expiration_month', models.CharField(blank=True, max_length=2, verbose_name='mes de expiración')),
                ('expiration_year', models.CharField(blank=True, max_length=4, verbose_name='año de expiración')),
                ('is_default', models.BooleanField(default=False, verbose_name='tarjeta predeterminada')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
                'db_table': 'user_cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
