# Generated by Django 4.2.29 on 2026-03-27 21:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('iva', 'IVA Chile (19%)'), ('mercadopago', 'Comisión Mercado Pago'), ('platform', 'Mantención Plataforma'), ('seller', 'Ganancias Vendedor'), ('revenue', 'Ingresos Netos Plataforma')], max_length=30, unique=True, verbose_name='tipo de cuenta')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='porcentaje')),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total créditos')),
                ('total_debits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total débitos')),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'finance_accounts',
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_number', models.CharField(max_length=30, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto bruto')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto neto')),
                ('payout_method', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('bank_transfer', 'Transferencia bancaria')], default='mercadopago', max_length=20, verbose_name='método de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True, verbose_name='notas admin')),
                ('failure_reason', models.TextField(blank=True, verbose_name='razón de fallo')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de pago',
                'verbose_name_plural': 'solicitudes de pago',
                'db_table': 'finance_payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution_number', models.CharField(max_length=30, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto bruto')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto IVA')),
                ('mercadopago_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='comisión Mercado Pago')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='comisión plataforma')),
                ('seller_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto vendedor')),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='products.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'distribución',
                'verbose_name_plural': 'distribuciones',
                'db_table': 'finance_distributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Venta'), ('iva', 'Cobro IVA'), ('mp_fee', 'Comisión Mercado Pago'), ('platform_fee', 'Comisión Plataforma'), ('seller_payout', 'Pago a Vendedor'), ('platform_profit', 'Ganancia Neta Plataforma'), ('refund', 'Reembolso'), ('deposit', 'Depósito')], max_length=30, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.paymentdistribution')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transacción financiera',
                'verbose_name_plural': 'transacciones financieras',
                'db_table': 'finance_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFinancialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ingresos totales')),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total IVA')),
                ('total_mercadopago_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total comisiones MP')),
                ('total_platform_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total comisiones plataforma')),
                ('total_seller_payouts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total pagos a vendedores')),
                ('period_sales', models.PositiveIntegerField(default=0)),
                ('period_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ingresos del período')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='products.category')),
            ],
            options={
                'verbose_name': 'resumen por categoría',
                'verbose_name_plural': 'resúmenes por categoría',
                'db_table': 'finance_category_summary',
            },
        ),
        migrations.AddIndex(
            model_name='paymentdistribution',
            index=models.Index(fields=['order'], name='finance_dis_order_i_3e689e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdistribution',
            index=models.Index(fields=['created_at'], name='finance_dis_created_67910a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdistribution',
            index=models.Index(fields=['status'], name='finance_dis_status_1bbcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['account', 'created_at'], name='finance_tra_account_b67846_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['user', 'created_at'], name='finance_tra_user_id_3de728_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type'], name='finance_tra_transac_53f2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['status'], name='finance_tra_status_75a5da_idx'),
        ),
    ]
