# Generated by Django 4.2.29 on 2026-03-20 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('category', models.CharField(choices=[('general', 'General'), ('technical', 'Técnico'), ('billing', 'Facturación'), ('refund', 'Reembolso')], default='general', max_length=50, verbose_name='categoría')),
                ('content', models.TextField(verbose_name='contenido')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'respuesta predefinida',
                'verbose_name_plural': 'respuestas predefinidas',
                'db_table': 'canned_responses',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'db_table': 'faqs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('helpful_yes', models.PositiveIntegerField(default=0)),
                ('helpful_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'artículo KB',
                'verbose_name_plural': 'artículos KB',
                'db_table': 'knowledge_base_articles',
                'ordering': ['-views', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría KB',
                'verbose_name_plural': 'categorías KB',
                'db_table': 'knowledge_base_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Técnico'), ('billing', 'Facturación'), ('sales', 'Ventas'), ('account', 'Cuenta'), ('product_inquiry', 'Consulta de producto'), ('refund', 'Reembolso'), ('partnership', 'Alianzas'), ('other', 'Otro')], default='other', max_length=20, verbose_name='categoría')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En progreso'), ('pending_response', 'Pendiente de respuesta'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='estado')),
                ('subject', models.CharField(max_length=300, verbose_name='asunto')),
                ('description', models.TextField(verbose_name='descripción')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], null=True)),
                ('satisfaction_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
                'db_table': 'ticket_attachments',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente'), ('system', 'Sistema'), ('note', 'Nota interna')], default='user', max_length=10, verbose_name='tipo')),
                ('content', models.TextField(verbose_name='contenido')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_internal', models.BooleanField(default=False, help_text='Las notas internas solo son visibles para el staff', verbose_name='nota interna')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
