# Generated by Django 4.2.29 on 2026-03-20 23:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(choices=[('regular', 'Licencia Regular'), ('extended', 'Licencia Extendida')], default='regular', max_length=20, verbose_name='tipo de licencia')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_add', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item del carrito',
                'verbose_name_plural': 'items del carrito',
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Cantidad fija'), ('free_shipping', 'Envío gratis')], default='percentage', max_length=20, verbose_name='tipo')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor del descuento')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='compra mínima')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='descuento máximo')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='usos máximos')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='usos por usuario')),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(verbose_name='válido desde')),
                ('valid_until', models.DateTimeField(verbose_name='válido hasta')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('used', 'Usado completamente'), ('expired', 'Expirado'), ('disabled', 'Deshabilitado')], default='active', max_length=20, verbose_name='estado')),
                ('is_first_purchase_only', models.BooleanField(default=False, verbose_name='solo primera compra')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='número de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='estado')),
                ('payment_method', models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal'), ('transfer', 'Transferencia')], max_length=20, verbose_name='método de pago')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comisión plataforma')),
                ('seller_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total para vendedores')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notas de administrador')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
                ('mercadopago_merchant_order_id', models.CharField(blank=True, max_length=100)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'órdenes',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='nombre del producto')),
                ('product_slug', models.CharField(max_length=200)),
                ('product_image', models.URLField(blank=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('license_type', models.CharField(default='regular', max_length=20, verbose_name='tipo de licencia')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seller_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=5)),
                ('download_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'item de orden',
                'verbose_name_plural': 'items de orden',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('download_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'descarga',
                'verbose_name_plural': 'descargas',
                'db_table': 'product_downloads',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='razón')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechanzado'), ('processed', 'Procesado')], default='pending', max_length=20, verbose_name='estado')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mercadopago_refund_id', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'reembolso',
                'verbose_name_plural': 'reembolsos',
                'db_table': 'refunds',
            },
        ),
    ]
