# Generated by Django 4.2.29 on 2026-03-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='platform_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA Chile'),
        ),
        migrations.AddField(
            model_name='order',
            name='mercadopago_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comisión Mercado Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_maintenance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='mantención plataforma'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mercadopago_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_maintenance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='pago neto vendedor'),
        ),
    ]
