# Generated by Django 4.2.29 on 2026-03-20 23:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='ícono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagen')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='meta título')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='meta descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('products_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='descripción corta')),
                ('description', models.TextField(verbose_name='descripción completa')),
                ('product_type', models.CharField(choices=[('software', 'Software'), ('template', 'Template'), ('course', 'Curso/Clase'), ('web_app', 'Aplicación Web'), ('mobile_app', 'Aplicación Móvil'), ('website', 'Página Web'), ('plugin', 'Plugin/Extensión'), ('component', 'Componente'), ('script', 'Script'), ('other', 'Otro')], default='software', max_length=20, verbose_name='tipo de producto')),
                ('license_type', models.CharField(choices=[('regular', 'Licencia Regular'), ('extended', 'Licencia Extendida'), ('commercial', 'Licencia Comercial')], default='regular', max_length=20, verbose_name='tipo de licencia')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio anterior')),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=products.models.product_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'pdf', 'exe', 'dmg'])], verbose_name='archivo principal')),
                ('demo_file', models.FileField(blank=True, null=True, upload_to=products.models.product_upload_path, verbose_name='demo/preview')),
                ('demo_url', models.URLField(blank=True, verbose_name='URL de demo')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='versión')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='fecha de lanzamiento')),
                ('last_update', models.DateField(blank=True, null=True, verbose_name='última actualización')),
                ('changelog', models.TextField(blank=True, verbose_name='historial de cambios')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='tecnologías')),
                ('frameworks', models.JSONField(blank=True, default=list, verbose_name='frameworks')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='lenguajes')),
                ('requirements', models.JSONField(blank=True, default=dict, verbose_name='requisitos')),
                ('supported_browsers', models.JSONField(blank=True, default=list, verbose_name='navegadores soportados')),
                ('supported_os', models.JSONField(blank=True, default=list, verbose_name='sistemas operativos')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='meta título')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='meta descripción')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='palabras clave')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='miniatura')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='razón de rechazo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_new', models.BooleanField(default=True, verbose_name='es nuevo')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='en oferta')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='permitir comentarios')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('has_regular_license', models.BooleanField(default=True)),
                ('regular_license_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio licencia regular')),
                ('has_extended_license', models.BooleanField(default=False)),
                ('extended_license_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio licencia extendida')),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('file', models.FileField(upload_to=products.models.product_upload_path)),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='tipo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='tamaño (bytes)')),
                ('is_downloadable', models.BooleanField(default=True, verbose_name='descargable')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'archivo de producto',
                'verbose_name_plural': 'archivos de productos',
                'db_table': 'product_files',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=products.models.product_image_path, verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de productos',
                'db_table': 'product_images',
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Muy malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], verbose_name='calificación')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('pros', models.JSONField(blank=True, default=list, verbose_name='ventajas')),
                ('cons', models.JSONField(blank=True, default=list, verbose_name='desventajas')),
                ('used_for', models.CharField(blank=True, max_length=100, verbose_name='uso del producto')),
                ('expertise_level', models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20, verbose_name='nivel de experiencia')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reseña',
                'verbose_name_plural': 'reseñas',
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_helpfulness',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'db_table': 'tags',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product')),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'db_table': 'user_favorites',
            },
        ),
    ]
